USE [BDEmpresaX]
GO

/****** Objeto: SqlProcedure [dbo].[spClienteInserir] Data do Script: 30/05/2024 11:56:57 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



--PROCEDURES CLIENTE
CREATE PROCEDURE spClienteInserir
    @NOME NVARCHAR(100),
    @CPF NVARCHAR(14),
    @ENDERECO NVARCHAR(200),
    @TELEFONE NVARCHAR(20),
    @EMAIL NVARCHAR(100),
	@RESULT INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO TB_CLIENTE (NOME, CPF, ENDERECO, TELEFONE, EMAIL)
    VALUES (@NOME, @CPF, @ENDERECO, @TELEFONE, @EMAIL);

	SELECT @RESULT = SCOPE_IDENTITY();
END
