USE [BDEmpresaX]
GO

/****** Objeto: SqlProcedure [dbo].[spVendasConsultarPorProduto] Data do Script: 30/05/2024 11:59:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO









CREATE PROCEDURE spVendasConsultarPorProduto
(
	@IDPRODUTO nvarchar(100) = NULL
)
AS
BEGIN
	SELECT V.IDVENDA,
		   C.IDCLIENTE, C.NOME,
		   P.IDPRODUTO, P.DESCRICAO
	FROM   TB_VENDAS V, TB_CLIENTE C, TB_PRODUTO P
	WHERE  V.IDPRODUTO = @IDPRODUTO
	AND    V.IDCLIENTE = C.IDCLIENTE
	AND    V.IDPRODUTO = P.IDPRODUTO;
END
